version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${DOCKER_USER:-laravel}
        uid: ${DOCKER_UID:-1000}
    container_name: ${APP_CONTAINER_NAME:-laravel-app}
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./vendor:/var/www/vendor
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME:-mysql}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test123  # This matches your current password
      MYSQL_DATABASE: task_management_system
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME:-nginx}
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-8000}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
